name: Docker Image CI
on: [push]
#  schedule:
#    - cron:  '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Golang
      uses: actions/setup-go@v1
      with:
        go-version: '1.10.x'
    - run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
        echo "${GOPATH}"
        id
        sudo mkdir -p "${GOPATH}"/src/github.com/kubeflow
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8.0'
    - name: Build the Docker image
       run: docker build . --file build/images/tf_operator/Dockerfile --tag localbuild/testimage:latest
#      run: |
#        sleep 60
#        echo "::set-env name=GOPATH::$(go env GOPATH)"
#        echo "::add-path::$(go env GOPATH)/bin"
#        pip install pipenv
#        cd py
#        cp kubeflow/tf_operator/Pipfile* .
#        pipenv install
#        pipenv run python -m kubeflow.tf_operator.release local
    - uses: anchore/scan-action@master
      with:
        image-reference: "localbuild/testimage:latest"
        dockerfile-path: "./build/images/tf_operator/Dockerfile"
        fail-build: false
    - name: anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done

